"""empty message

Revision ID: 5d761ae1f696
Revises: add_tracker_override_tables
Create Date: 2026-05-06 16:16:27.778274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d761ae1f696'
down_revision = 'add_tracker_override_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_cycles_tracker_id'))

    with op.batch_alter_table('tracker_field_overrides', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_tfo_tracker'))

    with op.batch_alter_table('tracker_option_overrides', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_too_tracker'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_option_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_too_tracker'), ['tracker_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('tracker_field_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tfo_tracker'), ['tracker_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('period_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_cycles_tracker_id'), ['tracker_id'], unique=False)

    # ### end Alembic commands ###
