"""add_settings_to_tracker

Revision ID: 6ebb9e7ab331
Revises: bbcfcd4afcd0
Create Date: 2025-11-11 17:00:26.974754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebb9e7ab331'
down_revision = 'bbcfcd4afcd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackers', schema=None) as batch_op:
        batch_op.drop_column('settings')

    # ### end Alembic commands ###
