"""add_unit_system_to_user

Revision ID: bbcfcd4afcd0
Revises: 3c4d5e6f7a8b
Create Date: 2025-11-11 12:08:59.785732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbcfcd4afcd0'
down_revision = '3c4d5e6f7a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_options', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_field_options_tracker_user_field'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tracker_user_fields', ['tracker_user_field_id'], ['id'])

    with op.batch_alter_table('tracking_data', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('tracking_data_tracker_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trackers', ['tracker_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_system', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('unit_system')

    with op.batch_alter_table('tracking_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tracking_data_tracker_id_fkey'), 'trackers', ['tracker_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('field_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_field_options_tracker_user_field'), 'tracker_user_fields', ['tracker_user_field_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
