"""Add TrackerField model for advanced field management

Revision ID: cb12f066afd3
Revises: 81f621019cb5
Create Date: 2025-10-04 14:53:23.008946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb12f066afd3'
down_revision = '81f621019cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_parent', sa.String(length=100), nullable=True),
    sa.Column('field_full_path', sa.String(length=200), nullable=True),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=True),
    sa.Column('display_label', sa.String(length=200), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=200), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('step', sa.Float(), nullable=True),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('choice_labels', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('display_options', sa.JSON(), nullable=True),
    sa.Column('field_order', sa.Integer(), nullable=True),
    sa.Column('field_group', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tracker_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_fields')
    # ### end Alembic commands ###
