"""Add FieldOption model and restructure TrackerField

Revision ID: fb880b9f9559
Revises: cb12f066afd3
Create Date: 2025-10-06 18:41:04.118922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb880b9f9559'
down_revision = 'cb12f066afd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_field_id', sa.Integer(), nullable=False),
    sa.Column('option_name', sa.String(length=100), nullable=False),
    sa.Column('option_type', sa.String(length=50), nullable=False),
    sa.Column('option_order', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('display_label', sa.String(length=200), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=200), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('step', sa.Float(), nullable=True),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('choice_labels', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('display_options', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tracker_field_id'], ['tracker_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracker_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tracker_fields', ['parent_id'], ['id'])
        batch_op.drop_column('default_value')
        batch_op.drop_column('display_options')
        batch_op.drop_column('is_optional')
        batch_op.drop_column('max_value')
        batch_op.drop_column('step')
        batch_op.drop_column('max_length')
        batch_op.drop_column('placeholder')
        batch_op.drop_column('choice_labels')
        batch_op.drop_column('is_required')
        batch_op.drop_column('choices')
        batch_op.drop_column('validation_rules')
        batch_op.drop_column('min_value')
        batch_op.drop_column('field_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('min_value', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('validation_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('choice_labels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('placeholder', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_length', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('step', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_value', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_optional', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('display_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default_value', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    op.drop_table('field_options')
    # ### end Alembic commands ###
